baseURL = "https://daysandmoons1.github.io/bayaba-hut/"
title = "Bayaba's Hut"
defaultContentLanguage = "ko"
hasCJKLanguage = true
theme = "PaperMod"
[pagination]
  pagerSize = 10
enableRobotsTXT = true
languageCode = "ko"
DefaultContentLanguageInSubdir = false

[languages]
  [languages.ko]
    languageName = "한국어"
    weight = 1
    title = "바야바의 움집"
    contentDir = "content/ko"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Bayaba's Hut"
    contentDir = "content/en"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  
[params.homeInfoParams]
  Title = "Bayaba's Hut"
  Content = "A blog where I document everything I've learned through life. ⛏️"

[params.assets]
  customCSS = ["css/custom.css"]

[params.comments]
enabled = true
github_username = "daysandmoons1"
github_repo = "blog-comments"

[outputs]
  home = [ "HTML" ]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"