name: Process Comments

on:
  issues:
    types: [opened, labeled]

jobs:
  process-comment:
    if: github.event.issue.labels.*.name == 'comment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PR from comment
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Add comment from ${{ github.event.issue.user.login }}'
          title: 'Comment: ${{ github.event.issue.title }}'
          body: |
            This PR was automatically created from a comment.
            Original issue: #${{ github.event.issue.number }}
            
            ${{ github.event.issue.body }}
          branch: comment-${{ github.event.issue.number }}
          base: main
          labels: comment, pending-review 